import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import CustomModal from '@/components/ui/modal/modal'
import { ModalProvider } from '@/hooks/useModal'
import { AuthProvider } from '@/providers/auth.provider'
import { NextUIProvider } from '@nextui-org/system'
import type { ReactNode } from 'react'
import { Toaster } from 'sonner'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextUIProvider>
          <ModalProvider>
            <AuthProvider>
              <Toaster />
              {children}
              <CustomModal />
            </AuthProvider>
          </ModalProvider>
        </NextUIProvider>
      </body>
    </html>
  )
}
